// Code generated by protoc-gen-go. DO NOT EDIT.
// source: boardgame.proto

package boardgame

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListBoardGamesRequest struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBoardGamesRequest) Reset()         { *m = ListBoardGamesRequest{} }
func (m *ListBoardGamesRequest) String() string { return proto.CompactTextString(m) }
func (*ListBoardGamesRequest) ProtoMessage()    {}
func (*ListBoardGamesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5da70b4f8529eca, []int{0}
}

func (m *ListBoardGamesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBoardGamesRequest.Unmarshal(m, b)
}
func (m *ListBoardGamesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBoardGamesRequest.Marshal(b, m, deterministic)
}
func (m *ListBoardGamesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBoardGamesRequest.Merge(m, src)
}
func (m *ListBoardGamesRequest) XXX_Size() int {
	return xxx_messageInfo_ListBoardGamesRequest.Size(m)
}
func (m *ListBoardGamesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBoardGamesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListBoardGamesRequest proto.InternalMessageInfo

func (m *ListBoardGamesRequest) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type ListBoardGamesResponse struct {
	BoardGames           []*BoardGame `protobuf:"bytes,1,rep,name=board_games,json=boardGames,proto3" json:"board_games,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListBoardGamesResponse) Reset()         { *m = ListBoardGamesResponse{} }
func (m *ListBoardGamesResponse) String() string { return proto.CompactTextString(m) }
func (*ListBoardGamesResponse) ProtoMessage()    {}
func (*ListBoardGamesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5da70b4f8529eca, []int{1}
}

func (m *ListBoardGamesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBoardGamesResponse.Unmarshal(m, b)
}
func (m *ListBoardGamesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBoardGamesResponse.Marshal(b, m, deterministic)
}
func (m *ListBoardGamesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBoardGamesResponse.Merge(m, src)
}
func (m *ListBoardGamesResponse) XXX_Size() int {
	return xxx_messageInfo_ListBoardGamesResponse.Size(m)
}
func (m *ListBoardGamesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBoardGamesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBoardGamesResponse proto.InternalMessageInfo

func (m *ListBoardGamesResponse) GetBoardGames() []*BoardGame {
	if m != nil {
		return m.BoardGames
	}
	return nil
}

type BoardGame struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BoardGame) Reset()         { *m = BoardGame{} }
func (m *BoardGame) String() string { return proto.CompactTextString(m) }
func (*BoardGame) ProtoMessage()    {}
func (*BoardGame) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5da70b4f8529eca, []int{2}
}

func (m *BoardGame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoardGame.Unmarshal(m, b)
}
func (m *BoardGame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoardGame.Marshal(b, m, deterministic)
}
func (m *BoardGame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoardGame.Merge(m, src)
}
func (m *BoardGame) XXX_Size() int {
	return xxx_messageInfo_BoardGame.Size(m)
}
func (m *BoardGame) XXX_DiscardUnknown() {
	xxx_messageInfo_BoardGame.DiscardUnknown(m)
}

var xxx_messageInfo_BoardGame proto.InternalMessageInfo

func (m *BoardGame) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BoardGame) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BoardGame) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *BoardGame) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*ListBoardGamesRequest)(nil), "ListBoardGamesRequest")
	proto.RegisterType((*ListBoardGamesResponse)(nil), "ListBoardGamesResponse")
	proto.RegisterType((*BoardGame)(nil), "BoardGame")
}

func init() { proto.RegisterFile("boardgame.proto", fileDescriptor_f5da70b4f8529eca) }

var fileDescriptor_f5da70b4f8529eca = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x4d, 0x3b, 0x84, 0xbe, 0xc2, 0x1c, 0x01, 0x67, 0xe9, 0xc5, 0xd2, 0x53, 0x45, 0xc8,
	0xa0, 0x9e, 0x3c, 0x4e, 0x11, 0x2f, 0x9e, 0xa2, 0xe0, 0x71, 0xa4, 0xcb, 0xb3, 0x04, 0xcc, 0x52,
	0x9b, 0xd4, 0x6f, 0xe4, 0xf7, 0x94, 0xa6, 0x6b, 0x41, 0x29, 0xec, 0xf6, 0x92, 0xfc, 0x7e, 0xbc,
	0xfc, 0xff, 0x70, 0x51, 0x19, 0xd1, 0xca, 0x5a, 0x68, 0x64, 0x4d, 0x6b, 0x9c, 0x49, 0xaf, 0x6b,
	0x63, 0xea, 0x4f, 0xdc, 0xf8, 0x53, 0xd5, 0x7d, 0x6c, 0x9c, 0xd2, 0x68, 0x9d, 0xd0, 0xcd, 0x00,
	0xe4, 0x37, 0x70, 0xf9, 0xa2, 0xac, 0x7b, 0xe8, 0xbd, 0x67, 0xa1, 0xd1, 0x72, 0xfc, 0xea, 0xd0,
	0x3a, 0xba, 0x82, 0x50, 0x49, 0x9b, 0x90, 0x2c, 0x2c, 0x22, 0xde, 0x8f, 0xf9, 0x13, 0xac, 0xff,
	0xa3, 0xb6, 0x31, 0x07, 0x8b, 0xf4, 0x16, 0x62, 0xbf, 0x78, 0xd7, 0x6f, 0x1e, 0x9c, 0xb8, 0x04,
	0x36, 0x91, 0x1c, 0xaa, 0x49, 0xca, 0x7f, 0x08, 0x44, 0xd3, 0x0b, 0x5d, 0x42, 0xa0, 0x64, 0x42,
	0x32, 0x52, 0x44, 0x3c, 0x50, 0x92, 0x52, 0x58, 0x1c, 0x84, 0xc6, 0x24, 0xf0, 0x37, 0x7e, 0xa6,
	0xf7, 0x00, 0xfb, 0x16, 0x85, 0x43, 0xb9, 0x13, 0x2e, 0x09, 0x33, 0x52, 0xc4, 0x65, 0xca, 0x86,
	0x64, 0x6c, 0x4c, 0xc6, 0xde, 0xc6, 0x64, 0x3c, 0x3a, 0xd2, 0x5b, 0xd7, 0xab, 0x5d, 0x23, 0x47,
	0x75, 0x71, 0x5a, 0x3d, 0xd2, 0x5b, 0x57, 0xbe, 0xc3, 0x6a, 0xfa, 0xe6, 0x2b, 0xb6, 0xdf, 0x6a,
	0x8f, 0xf4, 0x11, 0x96, 0x7f, 0x2b, 0xa0, 0x6b, 0x36, 0x5b, 0x5f, 0x7a, 0xc5, 0xe6, 0xbb, 0xca,
	0xcf, 0xaa, 0x73, 0xbf, 0xf7, 0xee, 0x37, 0x00, 0x00, 0xff, 0xff, 0x48, 0xb8, 0x8d, 0x2d, 0xad,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BoardGameServiceClient is the client API for BoardGameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BoardGameServiceClient interface {
	ListBoardGames(ctx context.Context, in *ListBoardGamesRequest, opts ...grpc.CallOption) (*ListBoardGamesResponse, error)
}

type boardGameServiceClient struct {
	cc *grpc.ClientConn
}

func NewBoardGameServiceClient(cc *grpc.ClientConn) BoardGameServiceClient {
	return &boardGameServiceClient{cc}
}

func (c *boardGameServiceClient) ListBoardGames(ctx context.Context, in *ListBoardGamesRequest, opts ...grpc.CallOption) (*ListBoardGamesResponse, error) {
	out := new(ListBoardGamesResponse)
	err := c.cc.Invoke(ctx, "/BoardGameService/ListBoardGames", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BoardGameServiceServer is the server API for BoardGameService service.
type BoardGameServiceServer interface {
	ListBoardGames(context.Context, *ListBoardGamesRequest) (*ListBoardGamesResponse, error)
}

// UnimplementedBoardGameServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBoardGameServiceServer struct {
}

func (*UnimplementedBoardGameServiceServer) ListBoardGames(ctx context.Context, req *ListBoardGamesRequest) (*ListBoardGamesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBoardGames not implemented")
}

func RegisterBoardGameServiceServer(s *grpc.Server, srv BoardGameServiceServer) {
	s.RegisterService(&_BoardGameService_serviceDesc, srv)
}

func _BoardGameService_ListBoardGames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBoardGamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoardGameServiceServer).ListBoardGames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BoardGameService/ListBoardGames",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoardGameServiceServer).ListBoardGames(ctx, req.(*ListBoardGamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BoardGameService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "BoardGameService",
	HandlerType: (*BoardGameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListBoardGames",
			Handler:    _BoardGameService_ListBoardGames_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "boardgame.proto",
}
