// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graghql

type Greet struct {
	Message string `json:"message"`
}

type Hello struct {
	Message string `json:"message"`
}

type Person struct {
	Name string `json:"name"`
}
